from google.adk.agents import Agent
from google.adk.tools import agent_tool
from .sub_agents.text_explainer import text_explainer_agent
from .sub_agents.flashcard_agent import flashcard_agent
from .sub_agents.video_suggester_agent import video_suggester_agent
from .sub_agents.content_composer_agent import content_composer_agent

root_agent = Agent(
    name="content_generator_agent",
    model="gemini-2.5-flash",
    description="Coordinates sub-agents to produce educational content",
    instruction="""
You are an educational content orchestrator.

1. When given a topic, use:
  - `text_explainer_agent` to generate explanation + bullet points
  - `flashcard_agent` to generate flashcards as a dictionary: "Question": "Answer"
  - `video_suggester_agent` to return relevant YouTube links

2. Then pass all this information to `content_composer_agent`, which will create a structured JSON with:
  - text_explanation
  - topics_summary
  - flashcards
  - video_suggestions

Return ONLY the JSON generated by the content_composer_agent.
""",
    tools=[
        agent_tool.AgentTool(agent=text_explainer_agent),
        agent_tool.AgentTool(agent=flashcard_agent),
        agent_tool.AgentTool(agent=video_suggester_agent),
        agent_tool.AgentTool(agent=content_composer_agent),
    ],
)
