from google.adk.agents import Agent
from google.adk.tools import agent_tool
from tools.save_uploaded_file import save_uploaded_file
from tools.upload_file_to_bucket import upload_file_to_bucket
from tools.extract_text_from_image import extract_text_from_image
from agents.essay_evaluator_agent.agent import root_agent as essay_agent

root_agent = Agent(
    name="image_to_essay_agent",
    model="gemini-2.5-flash",
    description="Extracts essay text from an image and sends it for automatic evaluation",
    instruction="""
You will receive an image submitted by the student. Follow these steps:
1. Use `save_uploaded_file(data, file_name)` to save the image locally.
2. Use `upload_file_to_bucket(file_path, file_name)` to upload the image to GCS (Google Cloud Storage).
3. Use `extract_text_from_image(url)` to extract the text via OCR.
4. Then, call `essay_evaluator_agent` tool, passing the extracted text for evaluation.
5. Return the evaluation result (JSON) generated by the essay evaluator agent. Return ONLY the JSON generated by the essay evaluator agent, IDENTICAL to the one returned by the essay evaluator agent. Do not change anything.
""",
    tools=[
        save_uploaded_file,
        upload_file_to_bucket,
        extract_text_from_image,
        agent_tool.AgentTool(agent=essay_agent),
    ],
)
